# Generated by Django 5.1.15 on 2026-08-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='initiated_by',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
