# Generated by Django 5.1.15 on 2026-08-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashback_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cashback the customer chose to put toward this order.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cashback_used_at',
            field=models.DateTimeField(blank=True, help_text='Set when this amount was deducted from the wallet (idempotency guard).', null=True),
        ),
    ]
