# Generated by Django 5.1.15 on 2026-08-10 12:46

import apps.catalog.models
from django.db import migrations, models


def backfill_product_pids(apps, schema_editor):
    """Assign a unique PID to every pre-existing product row.

    A callable default evaluates once per ALTER TABLE on SQLite, so every
    existing row would otherwise share the same PID and violate the unique
    constraint. Generate a distinct value per row here instead.
    """
    Product = apps.get_model("catalog", "Product")
    make_pid = Product._meta.get_field("pid").default
    seen = set()
    for product in Product.objects.all().iterator():
        pid = product.pid or make_pid()
        while pid in seen or Product.objects.filter(pid=pid).exists():
            pid = make_pid()
        seen.add(pid)
        Product.objects.filter(pk=product.pk).update(pid=pid)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.CharField(blank=True, default=apps.catalog.models._default_pid, help_text='Unique Product ID shown in the admin catalog.', max_length=24),
        ),
        migrations.RunPython(backfill_product_pids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(blank=True, default=apps.catalog.models._default_pid, help_text='Unique Product ID shown in the admin catalog.', max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded product photo (stored locally in dev, S3 in prod).', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
