# Generated by Django 5.1.15 on 2026-08-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_pid_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_unit',
            field=models.CharField(choices=[('kg', 'Kilograms (kg)'), ('count', 'Count (pieces)')], default='count', help_text='Unit for stock: kg for weight-based items, count for piece-based items.', max_length=8),
        ),
    ]
