# Generated by Django 5.1.15 on 2026-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_stock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded category image (stored locally in dev, S3 in prod).', null=True, upload_to='categories/'),
        ),
    ]
