# Generated by Django 5.1.15 on 2026-08-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='ref_order_id',
            field=models.CharField(blank=True, help_text='Order UUID that caused this movement (orders use UUID primary keys).', max_length=36, null=True),
        ),
    ]
