# Generated by Django 5.1.15 on 2026-08-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_sent_at',
        ),
    ]
