# Generated by Django 5.1.15 on 2026-08-11 14:42

import django.db.models.deletion
import uuid
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def backfill_existing_ledger(apps, schema_editor):
    """Anchor pre-existing ledger rows to a DebtBook and derive new fields.

    Every legacy row carries ``user_id`` + ``shop_id``. We create one DebtBook
    per (user, shop), derive ``entry_type`` from the sign of ``delta`` and
    rebuild the ``prev_balance`` → ``balance_after`` chain so existing debt data
    is preserved and readable by the new Debt Book UI.
    """
    DebtLedger = apps.get_model("wallet", "DebtLedger")
    DebtBook = apps.get_model("wallet", "DebtBook")
    User = apps.get_model("accounts", "User")

    books = {}
    for entry in DebtLedger.objects.iterator():
        if entry.delta > 0:
            entry.entry_type = "bill"
        elif entry.delta < 0:
            entry.entry_type = "payment"
        else:
            entry.entry_type = "adjustment"

        if entry.user_id is None:
            entry.save(update_fields=["entry_type"])
            continue

        key = (entry.user_id, entry.shop_id)
        book = books.get(key)
        if book is None:
            user = User.objects.filter(id=entry.user_id).first()
            book = DebtBook.objects.create(
                user_id=entry.user_id,
                shop_id=entry.shop_id,
                name=user.full_name if user else "",
                phone=user.phone if user else "",
            )
            books[key] = book
        entry.book = book
        entry.save(update_fields=["entry_type", "book"])

    # Rebuild the prev_balance chain (entries are already ordered desc; reverse).
    by_book = {}
    for entry in DebtLedger.objects.iterator():
        by_book.setdefault(entry.book_id, []).append(entry)
    for group in by_book.values():
        group.sort(key=lambda e: (e.created_at, str(e.id)))
        prev = Decimal("0.00")
        for entry in group:
            entry.prev_balance = prev
            prev = entry.balance_after
            entry.save(update_fields=["prev_balance"])


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('wallet', '0002_debtledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='debtledger',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtledger',
            name='entry_type',
            field=models.CharField(choices=[('bill', 'Debt added / goods on credit'), ('payment', 'Payment received'), ('adjustment', 'Adjustment / correction')], db_index=True, default='bill', max_length=20),
        ),
        migrations.AddField(
            model_name='debtledger',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debtledger',
            name='prev_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Outstanding before this transaction.', max_digits=10),
        ),
        migrations.AddField(
            model_name='debtledger',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='debtledger',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='debtledger',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='debtledger',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Outstanding remaining after this transaction.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='debtledger',
            name='delta',
            field=models.DecimalField(decimal_places=2, help_text='Positive = debt added, Negative = amount paid / correction downward', max_digits=10),
        ),
        migrations.AlterField(
            model_name='debtledger',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='debtledger',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created/updated this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debtledger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_ledger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DebtBook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Offline customer name.', max_length=150)),
                ('phone', models.CharField(blank=True, help_text='Offline customer phone.', max_length=15)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_books', to='shops.shop')),
                ('user', models.ForeignKey(blank=True, help_text='Verified customer account (set once the customer registers).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_book', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debt book',
                'verbose_name_plural': 'Debt books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='debtledger',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='wallet.debtbook'),
        ),
        migrations.AddIndex(
            model_name='debtledger',
            index=models.Index(fields=['book', '-created_at'], name='wallet_debt_book_id_534fba_idx'),
        ),
        migrations.AddField(
            model_name='debtnote',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='wallet.debtbook'),
        ),
        migrations.AddField(
            model_name='debtnote',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_notes_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='debtbook',
            index=models.Index(fields=['shop', '-created_at'], name='wallet_debt_shop_id_c7b07c_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtbook',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'shop'), name='uniq_debt_book_user_shop'),
        ),
        migrations.AddIndex(
            model_name='debtnote',
            index=models.Index(fields=['book', 'created_at'], name='wallet_debt_book_id_c550bd_idx'),
        ),
        migrations.RunPython(backfill_existing_ledger, migrations.RunPython.noop),
    ]
