# Generated by Django 5.1.15 on 2026-08-11 16:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


def backfill_bill_items(apps, schema_editor):
    """Mirror every existing single-product bill row as a DebtBillItem.

    Old bill ledger rows stored one product in their flat fields. Wrap each in
    a DebtBillItem so the multi-product bill structure (1 bill → N items) holds
    for historical data too — no history is lost or edited, only re-expressed
    under the new schema.
    """
    DebtLedger = apps.get_model("wallet", "DebtLedger")
    DebtBillItem = apps.get_model("wallet", "DebtBillItem")

    bills = DebtLedger.objects.filter(entry_type="bill").exclude(book_id__isnull=True)
    for bill in bills.iterator():
        qty = bill.quantity or 1
        price = bill.unit_price or Decimal("0")
        disc = bill.discount or Decimal("0")
        DebtBillItem.objects.create(
            bill=bill,
            product_name=bill.product_name,
            quantity=qty,
            unit="count",
            unit_price=price,
            discount=disc,
            line_total=(Decimal(qty) * Decimal(price) - Decimal(disc)).quantize(Decimal("0.01")),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_image'),
        ('wallet', '0003_debtnote_debtledger_discount_debtledger_entry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtbook',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Offline customer contact email (e.g. Gmail).', max_length=254),
        ),
        migrations.AddField(
            model_name='debtledger',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid at the counter when this bill was created.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='debtbook',
            name='phone',
            field=models.CharField(blank=True, help_text='Offline customer phone (10 digits).', max_length=15),
        ),
        migrations.CreateModel(
            name='DebtBillItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('count', 'count')], default='count', max_length=8)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wallet.debtledger')),
                ('product', models.ForeignKey(blank=True, help_text='Optional catalog product this line was selected from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_bill_items', to='catalog.product')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(backfill_bill_items, migrations.RunPython.noop),
    ]
