# Generated by Django 5.1.15 on 2026-08-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_debtbook_email_debtledger_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletledger',
            name='reason',
            field=models.CharField(choices=[('purchase_cashback', 'Purchase cashback'), ('voucher_mint', 'Voucher mint'), ('cashback_redeemed', 'Cashback redeemed'), ('adjustment', 'Adjustment')], default='purchase_cashback', max_length=20),
        ),
    ]
