# Generated by Django 5.1.15 on 2026-08-12 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_refund_and_more'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number_encrypted', models.TextField(help_text='AES-GCM ciphertext of the account number.')),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('ifsc', models.CharField(blank=True, max_length=11)),
                ('is_active', models.BooleanField(default=True, help_text='Account status (active / inactive).')),
                ('shop', models.ForeignKey(blank=True, help_text='Shop whose payout account this is (admin managed).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='shops.shop')),
                ('user', models.ForeignKey(blank=True, help_text='Customer who owns this account (self managed).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank account',
                'verbose_name_plural': 'Bank accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', '-created_at'], name='payments_ba_shop_id_242727_idx'), models.Index(fields=['user', '-created_at'], name='payments_ba_user_id_505e83_idx')],
            },
        ),
    ]
