# Generated by Django 5.1.15 on 2026-08-14 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method_order_payment_status_and_more'),
        ('payments', '0003_bankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='True when this payment was simulated by the demo gateway (no real money moved).'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='Payment gateway that processed this payment (demo | razorpay).', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Gateway transaction / reference ID.', max_length=64),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('emi', 'EMI'), ('demo_upi', 'Demo UPI'), ('demo_card', 'Demo Card'), ('demo_gpay', 'Demo GPay'), ('demo_phonepe', 'Demo PhonePe'), ('demo_paytm', 'Demo Paytm'), ('cod', 'Cash on Delivery')], default='upi', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='created', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
    ]
